- frameworks/TunedRandomForest/exec.py
- resources/frameworks.yaml
@PGijsbers please have a check and tell me if you agree with those changes.
I tried it with some of the small and medium datasets.
Haven't seen any significant change in picking `max_features` for  small ones, but it allows to build more models with different `mtry` in case of larger ones.
> TunedRF: lower #trees during tuning and tune with ascending mtry

- requirements.txt
Updated constraint to avoid error with arff library. Scipy 1.3 was not using the liac-arff library as required by the code.
> updated scipy version constrant in requirements.txt

- automl/docker.py
- automl/resources.py
https://github.com/openml/automlbenchmark/issues/20
In default `auto` setup mode, when running benchmark locally in docker mode, app was checking for existence of the image in local docker repository but not in remote repository before deciding to build it locally.
Fixed by adding a `docker pull` step if the image doesn't exist in local repository.
> ISSUE-20: try to pull remote image before trying to build it locally in default setup mode

- automl/aws.py
- examples/aws/config.yaml
- examples/config.yaml
- examples/custom/README.md
- examples/custom/config.yaml
https://github.com/openml/automlbenchmark/issues/22
In AWS support, some URL path elements are joined using `os.path.join`, leading to invalid path on Windows.
use `posixpath.join` when joining url path elements instead of `os.path.join`
> ISSUE-22: 

- automl/resources.py
- examples/custom/config.yaml
- resources/config.yaml
- runbenchmark.py
Removing relative paths in the `config.yaml` makes default paths behave similarly to custom `{user}` paths.
Main benefit is that the `runbenchmark.py` script can be now executed from anywhere (not required to have `cwd` in the main app folder.
> Improvement: remove relative paths to resource files

- automl/utils.py
Namespace class is ubiquitous in the code to represent configuration, framework definitions, benchmark definitions and more.
Due to high level of nested objects in those namespaces, they are hard to read in the logs: let's pretty print them.
Use this occasion to simplify the class.
> Minor improvement: simplify Namespace class and pretty print it

- resources/benchmarks/test.yaml
test on AWS is using hardcoded ec2 T3 series (available only in VPC)
> Test benchmark on AWS: removing hardcoded ec2_instance_type

- automl/aws.py
- resources/config.yaml
- runbenchmark.py
When running app from a different folder than the application root directory, the benchmark parameter is incorrect when running on AWS: this is annoying when extending the benchmark with private frameworks (which are usually placed outside the `automlbenchmark` app).
> Fixing path issue when running on aws from subfolder

- automl/aws.py
- resources/config.yaml
if `aws.minimize_instances` is set to true, this will create an aws job for each benchmark task (this job will run all the folds), instead of having an aws job per task+fold.
This is especially useful for frameworks that take a long time to setup.
The framework integration should however ensure that it is correctly started/shutdown before/after each fold.
> Adding config param to allow reuse of ec2 instances when running multiple instances.

- frameworks/ranger/setup.sh
public key for R repo was ignored, therefore default ubuntu R 3.4.4 version was always installed
> fixed key for CRAN repository (ranger integration example)

- automl/benchmark.py
- automl/docker.py
- automl/logger.py
- automl/utils.py
- frameworks/AutoWEKA/exec.py
- frameworks/ranger/exec.py
adding live console display for long-running commands when using `run_cmd`.
The main utility is when building docker images as we're blind otherwise and can't see issues that may block docker.
> Live display for some subprocesses when using `run_cmd`

- resources/benchmarks/validation.yaml
Adding a couple of datasets causing errors on few frameworks.
Should be useful when testing new framework integrations.
> extending validation dataset for frameworks integration

- .dockerignore
- .gitignore
- amlb/aws.py
- amlb/benchmark.py
- amlb/docker.py
- amlb/resources.py
- frameworks/H2OAutoML/exec.py
- frameworks/shared/setup.sh
- frameworks can create a virtualenv `venv` under their package folder.
- automlbenchmark app creates a virtualenv `venv` under its folder (esp. in docker, aws).
This allows auto-detection of python/pip executables in a hierarchical way depending on which command is being executed.
> Improve and standardize usage of virtual environments in the app

- frameworks/autosklearn/__init__.py
- frameworks/autosklearn/exec.py
- frameworks/autosklearn/requirements.txt
- frameworks/autosklearn/setup.sh
- frameworks/shared/callee.py
- resources/frameworks.yaml
This pull request is related to #84 
It moves autosklearn version to v0.6.0.
I also took advantage and move autosklearn to the venv feature, following the recommendation given in above issue.
It is important to note that I had to add some procs to frameworks/shared/callee.py that might benefit other frameworks, yet added some custom memory management inside auto-sklearn (that required psutil).
This has been tested in autosklearn -m local and -m docker. I also ran RandomForest to make sure nothing is broken.
> Moving sklearn to v0.6.0

- amlb/aws.py
- resources/config.yaml
added Name tag for the AWS EC2 console
collect various info about instance (e.g. public IP)
allow passing security group and key pair to allow ssh access, esp. useful to check on hanging instances.
> improve monitoring of aws instances

- amlb/singularity.py
This push addresses the issue mentioned on #92 
The problem statement is that singularity sometimes doesn't translate the docker workdir very well, and we want to enforce it with the pwd directive
> Force /bench workdir in singularity

- frameworks/AutoGluon/exec.py
models artifacts are unnecessary in a usual benchmark context and can use a lot of space + bandwidth (esp. in AWS mode: EC2+S3+network...) 
user can still keep/download models artifacts by creating a virtual framework in his custom `frameworks.yaml` file, for example:
```
autogluon:
module: frameworks.AutoGluon
version: '0.0.9'
params:
_save_artifacts: ['leaderboard', 'info', 'models']
```
> remove unnecessary AutoGluon artifacts by default

- frameworks/TPOT/exec.py
TPOT didn't have any mapping for `rmse` (which we use as default metric for regression)
> TPOT: fix metric mapping for regression

- amlb/benchmark.py
- amlb/utils/process.py
- frameworks/H2OAutoML/exec.py
activated using `-Xf._monitor_backend=True`
or
```
H2OAutoML:
extends: H2OAutoML
params:
_monitor_backend: true
```
> Offer an option to monitor h2o memory usage during benchmark

- amlb/benchmark.py
- amlb/results.py
Note that passing custom framework params on command line works only in local mode, those params are not propagated to docker or ec2 instances in docker and aws modes.
Example, to change `n_estimators` when using `randomforest`:
```
python runbenchmark.py randomforest -Xf.n_estimators=50
```
https://github.com/openml/automlbenchmark/issues/106
See discussion there though to properly run frameworks with custom params in docker and/or AWS.
Also added support for additional custom columns in results.
> Fix params in results when passing custom framework params on command line.

- frameworks/H2OAutoML/exec.py
This request is related to #107 and it only makes sure that the h2o runs are isolated.
To do so we condition on the PID to build the port number.
> Fix port configuration in H2O for multiple runs

- frameworks/shared/caller.py
now that live_output is working correctly for frameworks running in subprocess, ensure that subprocess logs are not printed twice on the console
> Prevent duplicate logging for frameworks running in subprocess

- amlb/benchmark.py
- amlb/resources.py
- resources/config.yaml
the `setup_args` used mainly in custom framework definitions didn't allow representation as array (better for self-documentation)
> support multiple setup args as array

- amlb/aws.py
on aws, disable the deletion of the config_scripts_user flag file.
this was added when thinking about instance reuse, but is annoying now when trying to restart a failed instance.
> Allow simple restart of failed Ec2 instances

- frameworks/H2OAutoML/exec.py
Ensure that we keep some memory for XGBoost in H2OAutoML.
H2O manages the JVM memory, but XGBoost uses native memory, hence the necessity tokeep some memory aside for XGBoost.
Also need to verify if other frameworks using xgboost don't have this same problem.
> H2OAutoML framework OoM issues

- amlb/data.py
- frameworks/autosklearn/__init__.py
for frameworks using encoded data, ensure that all non-numerical columns are encoded (not only categorical ones).
This is a quickfix/improved semantic before implementing https://github.com/openml/automlbenchmark/issues/116
> Ensure all non-numerical columns are encoded

- amlb/benchmark.py
- amlb/docker.py
- amlb/job.py
- amlb/results.py
- amlb/singularity.py
- amlb/utils/core.py
- amlb/utils/process.py
- amlb/utils/time.py
- frameworks/AutoGluon/exec.py
- frameworks/H2OAutoML/exec.py
- frameworks/TPOT/exec.py
- frameworks/autosklearn/exec.py
reviewed too broad usages of except (catching BaseException only to ensure that subprocesses can be cleaned).
ensure that one single  KBI allows to safely stop all running instances in AWS mode.
> KeyboardInterrupt should interrupt the entire benchmark

- amlb/aws.py
- amlb/benchmark.py
- amlb/results.py
https://github.com/openml/automlbenchmark/issues/117
adding 2 columns to `results.csv` files: 
- `metric` : the one as objective function, and corresponding to the `results` value
- `constraint`: to identify the constraint used for the given run.
> extend results with constraint and metric name

- amlb/aws.py
- amlb/results.py
- amlb/utils/os.py
- frameworks/AutoGluon/exec.py
- frameworks/H2OAutoML/exec.py
- frameworks/TPOT/exec.py
- frameworks/autosklearn/exec.py
- frameworks/shared/callee.py
- resources/frameworks.yaml
Archive artifacts when it leads to too much network traffic, especially too many files (from ec2 to s3, and then to local computer): esp. for H2OAutoML and AutoGluon.
At the same occasion, now that `amlb.utility` functions can be aliased in `callee.py` (they mainly rely only on python standard library), removed the duplicate  utility functions that were originally copied in `callee.py`
> Archive framework artifacts 

- frameworks/mljarsupervised/exec.py
@pplonski a small fix for macOS. I had the change locally, forgot to mention.
> fix matplotlib config to run with basic python on macOS

- frameworks/hyperoptsklearn/exec.py
- resources/frameworks.yaml
https://github.com/openml/automlbenchmark/issues/146
ensure hyperoptsklearn is using default algo, and provide a way to change this algo declaratively like for other params.
User can also change the algo by creating a custom framework definition:
```yaml
hyperoptsklearn_tpe:
extends: hyperoptsklearn
params:
max_evals: 1000
algo: hyperopt.tpe.suggest
```
and then run
```bash
python runbenchmark.py hyperoptsklearn_tpe
```
see https://github.com/openml/automlbenchmark/blob/master/docs/HOWTO.md#framework-definition for details.
> Ensure that hyperoptsklearn is using the default config (outside constraints).

- frameworks/shared/caller.py
Fix to support use case where the subprocess saves the predictions file in the correct format: for example https://github.com/openml/automlbenchmark/pull/153
> ensure that the caller simply ignores predictions params if output_file is set to None

- frameworks/shared/caller.py
Some frameworks may need to spawn new processes from libraries installed on their virtual env (e.g. python3, tpot, ...): see https://github.com/openml/automlbenchmark/pull/153
> ensure that the callee subprocess has its venv/bin in the PATH

- requirements.txt
blocker for new users running app locally on `master` branch (aws and docker modes don't use `master` branch by default, so got undetected).
> upgrade liac-arff, older version prevents correct parsing since openml upgrade

- resources/frameworks.yaml
Updating mljar-supervised version to 0.6.0. Is there an option to use the latest version from github or pypi?
> update mljar-supervised version to 0.6.0

- amlb/aws.py
- amlb/benchmark.py
- amlb/benchmarks/file.py
- amlb/benchmarks/openml.py
- amlb/benchmarks/parser.py
- amlb/resources.py
- docs/HOWTO.md
- docs/README.md
- resources/config.yaml
- runbenchmark.py
When specifying the benchmark to run any integer name is interpreted as an openml study.
E.g. `python runbenchmark.py constantpredictor openml/s/218`.
An unnecessary amount of meta-data is still downloaded, which is (mostly) due to openml tasks not having the associated dataset name. 
I'm looking for feedback. For example:
- Allowing a study id instead of benchmark name seems natural to me, but do you foresee problems? The only thing I can think of is 
- I think I found the best place to do the conversion, but is there a better spot?
- I am not entirely sure why the `Namespace` are used, but I simply adopted it. Does this seem reasonable?
Related to #61. However uses the study directly instead of writing to intermediate file. 
If approved I'll add/update docs.
> Allow an OpenML suite to define tasks of benchmark

- amlb/results.py
- docs/HOWTO.md
- docs/README.md
- resources/config.yaml
When framework was providing the combination:
```python
prediction_labels=["b", "a"]
target_encoded=True
```
with therefore "b" encoded as 0, "a" encoded as 1.
Then the `amlb` app was reordering prediction columns to get ["a", "b"], but it was not reencoding predictions and truth values, so that 1 was then meaning "b" instead of "a" after the reordering.
This PR fixes this issues, and ensures that values are re-encoded if needed.
> Reencode truth and predictions to match labels lexicographic order

- amlb/results.py
As far as I could tell, the custom metric could be used for optimization, but was never reported.
I set up a separate branch because I wasn't sure if this was correct (maybe I misinterpreted the documentation on the pr).
In general, we can expect AutoML frameworks to expect different signatures for their metric function. For example, TPOT requires a scikit-learn scorer: 
```python
from sklearn.metrics import make_scorer
def my_custom_accuracy(y_true, y_pred):
y_true = y_true.ravel()  # amlb provides a (N,1)-vector but we need (N,)
y_pred = y_pred.ravel()  # probably not required
score = float(sum(y_pred == y_true)) / len(y_true)
return score
foo = make_scorer(my_custom_accuracy, greater_is_better=True)
```
However we want a uniform signature for our own score calculations. So in addition …
> Allow custom metrics to be reported in results

- amlb/framework_definitions.py
- amlb/resources.py
- tests/conftest.py
- tests/unit/amlb/framework_definitions/test_framework_definition_processing.py
- tests/unit/amlb/resources/test_framework_definition.py
module name was forced to lowercase by default, preventing correct loading
```
python runbenchmark.py autogluon
Running `autogluon` on `test` benchmarks in `local` mode.
...
No module named 'frameworks.autogluon'
Traceback (most recent call last):
File "runbenchmark.py", line 111, in <module>
bench = amlb.Benchmark(args.framework, args.benchmark, args.constraint)
File "/Users/seb/repos/ml/automlbenchmark/amlb/benchmark.py", line 78, in __init__
self.framework_module = import_module(self.framework_def.module)
File "/Users/seb/.pyenv/versions/3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in …
```
> Fix module loading

- amlb/framework_definitions.py
- tests/unit/amlb/framework_definitions/test_add_default.py
This is required for docker images.
(Issue identified by @mwever in #179)
> Ensure the image name is all lower case

- resources/constraints.yaml
run 2 folds by default in test mode to ensure that all rows from the dataset get through the training process
> Run 2 folds by default when using (default) test constraint

- resources/frameworks.yaml
- tested frameworks are now ordered alphabetically in `frameworks.yaml`.
- all framework definitions witth the (exact) name of the framework must have no param set.
- frameworks providing a high-level switch, can provide 2 definitions:
- a default one (see above).
- (optional) one with an extended name, with the high-level switch/param.
> Standardize framework definitions

- amlb/benchmark.py
- amlb/framework_definitions.py
- amlb/resources.py
- amlb/results.py
- amlb/runners/aws.py
- amlb/runners/container.py
- resources/config.yaml
- runbenchmark.py
- runscores.py
- tests/conftest.py
- tests/unit/amlb/framework_definitions/test_load_and_merge_framework_definitions.py
All the path/files generated by the app must have an easily parseable name to extract meta information.
Until now, tokens were separated by an underscore character.
However, framework names, benchmark names, constraint names, task names often include an underscore or a dash, making those bad delimiters.
This PR uses dot a as a delimiter, and updates the regexp used internally to fetch and extract information from those files.
a config entry `token_separator` (now defaulting to ".") was added for backwards support.
> change file token separator from underscore to dot

- frameworks/H2OAutoML/exec.py
For datasets like dresses-sales (https://www.openml.org/t/125920), with numeric target classes (here: 1, 2), H2O prefixes the probabilities columns with `p` (p1, p2...) which breaks the computation of final metrics.
This didn't occur until recently as we only started to use H2O predictions columns since https://github.com/openml/automlbenchmark/pull/191
> fix H2O predictions formatting for target categories with numerical values

- amlb/datasets/openml.py
An example of dataset that was not handled correctly by the app: https://www.openml.org/d/4541
Applied a hack to the arff library to quote single question marks when writing arff files.
Will also create a ticket on the liac-arff library as this a bug imo.
Scenario is:
- arff file with quoted question marks as categorical values and data: e.g. 
```@attribute feat1 {'?', 'A', 'B', 'C'}```
- `arff.load()` reads those `'?'` as strings.
- `arff.write()` then writes the `'?'` from loaded data without quotes: ```@attribute feat1 {?, A, B, C}```
- `arff.load()` the last file interpretes `?` as missing value (`None`)
> Handle datasets with '?' as categorical value

- amlb/data.py
- amlb/datautils.py
- tests/unit/amlb/datautils/test_encoder.py
The application was already trimming all categorical values to support datasets like https://www.openml.org/d/4535 (see https://github.com/openml/automlbenchmark/pull/191).
Now some "unclean" datasets like https://www.openml.org/d/23381 have features like:
```
@attribute V2 {bohemian,Brief,Casual,cute,fashion,Flare,Novelty,OL,party,sexy,Sexy,vintage,work}
```
with "sexy" present twice but with a different case (also in the data), whereas the openml data provide only one version, creating a discrepancy in the application logic when encoding those categoricals.
To prevent this, the app now converts categorical values to lowercase to make sure they're case insensitive.
*N.B.*, this may also create an advantage for this majority of frameworks for which the application is preparing the data …
> Normalize categorical values

- amlb/benchmark.py
- amlb/datautils.py
- amlb/job.py
- amlb/runners/aws.py
- amlb/utils/core.py
- amlb/utils/time.py
- resources/config.yaml
https://github.com/openml/automlbenchmark/issues/150
Spot usage should be activated in user's config file, here is the list of new config points:
```yaml
aws:
ec2:
spot:
enabled: false             # if enabled, aws mode will try to obtain a spot instance instead of on-demand.
block_enabled: false       # if enabled, and if spot is enabled, aws mode will try to use block instances (possible only if total instance runtime <= 6h, i.e. for benchmark runtime up to 4h).
max_hourly_price: ''       # the max hourly price (in dollar) per instance to bid (defaults to on-demand price).
retry_policy: 'exponential:300:2:10800'  # use "constant:interval", "linear:start:increment:max" or "exponential:start:factor:max"
max_attempts: 10
fallback_to_on_demand: false             # if couldn't obtain a spot …
```
> Add support for Spot instances to AWS mode

- amlb/results.py
- frameworks/DecisionTree/exec.py
- frameworks/GAMA/exec.py
- frameworks/H2OAutoML/exec.py
- frameworks/MLPlan/exec.py
- frameworks/RandomForest/exec.py
- frameworks/TPOT/exec.py
- frameworks/TunedRandomForest/exec.py
- frameworks/autosklearn/exec.py
- frameworks/autoxgboost/exec.R
- frameworks/autoxgboost/exec.py
- frameworks/constantpredictor/exec.py
- frameworks/hyperoptsklearn/exec.py
- frameworks/mljarsupervised/exec.py
- frameworks/oboe/exec.py
- frameworks/ranger/exec.R
- frameworks/ranger/exec.py
- frameworks/shared/callee.py
- frameworks/shared/caller.py
https://github.com/openml/automlbenchmark/issues/162
Current issues:
- Not able to extract prediction time for frameworks that don't provide a separate  method/call to predict on a dataset:
- MLPlan (cc: @mwever)
- AutoWeka
- current support penalizes frameworks whose predict API loads the data from the file system, vs. those who load data separately and for which the prediction duration includes (as expected) *only* the prediction computation. Penalized frameworks:
- GAMA (cc: @PGijsbers)
> Extract prediction time and expose to results file.

- resources/config.yaml
increase default activity timeout to allow installation of large libraries when building docker image
> increase default activity timeout

- amlb/benchmarks/openml.py
While we lose the official dataset description, this puts a lot less strain on the server as not each dataset metadata is downloaded individually.
> Download less dataset metadata when loading openml suite

- frameworks/autosklearn/exec.py
This PR adds support for pre-release versions of Auto-sklearn and works around the package `packaging` apparently not being able to parse version identifiers following [PEP440](https://www.python.org/dev/peps/pep-0440/) but instead returning incomparable objects of type `LegacyVersion`.
I've also pushed a pre-release that I'd like to be used for the benchmark (see [here](https://pypi.org/project/auto-sklearn/0.12.1rc1/)), but I don't know how to make that available.
> allow using pre-release versions

- amlb/benchmark.py
- amlb/job.py
- amlb/runners/aws.py
- amlb/runners/container.py
- runbenchmark.py
Add the `-e` parameter to allow an error of a job to propagate back up and terminate the execution of `runbenchmark.py`. 
Used in Github Workflow (work in progress) to correctly identify failed evaluations. Also useful if you don't want to run subsequent tasks if one fails.
> Allow exit on error of a job

- amlb/runners/aws.py
- resources/config.yaml
When using a high level of parallelism in AWS mode, the IPs are released only when  the instance is fully terminated.
This PR applies the following changes:
- when terminating an instance, wait for the instance to be fully terminated before starting a new job/instance.
- if there are insufficient IPs, reschedule the job
> AWS Mode: retry job on insufficient ips

- amlb/datasets/file.py
- examples/custom/benchmarks/filedatasets.yaml
when dataset is defined as a list of remote files, only download needed files: the previous logic was downloading all listed files even if only 1 fold was used for example.
> Non-openML datasets: download only needed files

- amlb/benchmark.py
- amlb/runners/aws.py
- amlb/utils/process.py
- docs/HOWTO.md
- frameworks/shared/callee.py
- frameworks/shared/caller.py
- resources/config.yaml
- runbenchmark.py
The existing logic was not always able to interrupt the job, especially if the framework was running in a subprocess.
Therefore the subprocess (`callee.py`) now handles its own interruption logic, raising an error in the main thread and cleaning up the sub-subprocesses if any.
The job interruption is then delayed by 1 min to let the subprocess handle its own interruption and propagate the errors correctly and generate  an entry in the `results.csv` file.
> Improve job/framework interruption after hard timeout.

- docs/HOWTO.md
Also fix an error where the nightly_h2o build did not actually contain a setup_cmd that was referred to.
I didn't include the old description since it's not in the `examples/custom/frameworks.yaml`.
> Add 'add documentation' step to PR instructions

- .gitattributes
- amlb/resources.py
- amlb/utils/process.py
There were a few issues with using docker mode `-m docker` in Windows.
The main pitfalls were:
- default git behavior checking out `.sh` files locally with `crlf` ending, which can't be executed by a bash shell.
- live output monitoring using `select` which is not supported for file descriptors in Windows.
I could not find a proper supported way to monitor process output non-blocking in Windows (without resorting to a new package), so I made a custom function based on various solutions proposed on StackOverflow.
Also fixes a bug where `git` was not detected due to `2>/dev/null` in a command, which does not work on Windows.
If that error ignoring was desirable, I can make it platform specific (I think my fix preserves the intended functionality, but I might have missed the point).
Tested …
> Docker for Windows

- .travis.yml
- amlb/benchmark.py
- amlb/job.py
- amlb/results.py
- amlb/runners/aws.py
- amlb/utils/core.py
- amlb/utils/process.py
- concat_csv.py
- pytest.ini
- tests/unit/amlb/job/dummy.py
- tests/unit/amlb/job/test_MultiThreadingJobRunner.py
- tests/unit/amlb/job/test_SimpleJobRunner.py
- tests/unit/amlb/utils/process/test_InterruptTimeout.py
Fixed race condition when multiple jobs terminate at the same time: common with high parallelism.
Partially rewrote the job runner to be more robust and predictable, especially when using Spot instances where job rescheduling is sometimes required.
- now using a proper state machine.
- generic hooks when the job change state.
- job state change hooks used in aws mode to trigger cleanup logic, rescheduling, …
Added test suites for job runners and rescheduling mechanism.
> Job Runner v2

- amlb/results.py
- amlb/runners/aws.py
- amlb/utils/core.py
Ensure that there is an entry in the failures file for each job for which we can't obtain a `results.csv` file.
Frameworks errors should be handled by the job on the remote instance and always produce an entry in the `results.csv` including a short description of the error.
Which means that if there's no  `results.csv` available, then the job failed for unkown reason and it's reasonable to consider that it could  be rerun later once we have a mechanism to load the `failures.csv` file for such reruns.
> Add failures entry on missing result

- frameworks/shared/callee.py
Replaced calls to print by logger in callee.py
> Calls to print mixed up with framework logs.

- amlb/frameworks/definitions.py
- amlb/resources.py
- resources/frameworks.yaml
- resources/frameworks_2020Q2.yaml
- resources/frameworks_latest.yaml
- resources/frameworks_stable.yaml
- tests/unit/amlb/frameworks/definitions/resources/frameworks_inheritance.yaml
- tests/unit/amlb/frameworks/definitions/test_load_framework_definitions.py
- tests/unit/amlb/resources/test_framework_definition.py
This is mainly useful to define a "template" framework from which children could extend to inherit all its properties without wanting to be able to run the template itself.
A typical use-case is MLPLan that comes with 2 training engines.
> Add the possibility to declare a framework as abstract

- frameworks/autosklearn/exec.py
The current version does incorrectly not pass the calculated memory limit to Auto-sklearn for versions >= 0.11 which makes Auto-sklearn fall back to a default memory limit. This PR adds the calculated memory limit to the constructor arguments.
> Pass memory limit to Auto-sklearn

- amlb/runners/aws.py
The `delay_between_jobs` config param was moved under `job_scheduler` in [this commit](https://github.com/openml/automlbenchmark/blob/cea54d78bba2b7746344cc796c3e40939c07fb7f/resources/config.yaml#L63) which causes this error when running the benchmark in parallel `-p` on AWS:
```
'Namespace' object has no attribute 'delay_between_jobs'
Traceback (most recent call last):
File "runbenchmark.py", line 142, in <module>
res = bench.run(args.task, args.fold)
File "/home/ledell/github/automlbenchmark/amlb/runners/aws.py", line 201, in run
return super().run(task_name, fold)
File "/home/ledell/github/automlbenchmark/amlb/benchmark.py", line 199, in run
results = self._run_jobs(jobs)
File "/home/ledell/github/automlbenchmark/amlb/benchmark.py", line 222, in _run_jobs
self.job_runner = …
```
> Fix config bug with delay_between_jobs

- frameworks/TunedRandomForest/setup.sh
`Stopit` module is used to ensure fitting normally stops in reasonable time for
Tuned Random Forest to return a model. For whatever reason it seemed to
no longer be installed.
> Install requirements.txt for Tuned Random Forest

- amlb/job.py
Ensure that return statements are executed outside finally blocks to avoid swallowing exceptions
> ensure that return statements are executed outside finally blocks to

- frameworks/AutoGluon/setup.sh
This updates AutoGluon to support the latest release, [0.2.0](https://github.com/awslabs/autogluon/releases/tag/v0.2.0).
Instead of specifying sklearnex as an optional dependency in the install as we would normally do, I've made it installed on its own prior so AutoGluon 0.1.0 can still be run without issue.
> Update AutoGluon to 0.2.0

- frameworks/AutoWEKA/setup.sh
- frameworks/MLPlan/__init__.py
- frameworks/MLPlan/exec.py
- frameworks/MLPlan/setup.sh
* Added feature for returning the time taken for making the predictions with the finally chosen candidate.
Note: ML-Plan takes the time for fitting the finally chosen solution candidate into account and tries to meet the timeout including fitting the solution. The prediction time for the test data, however, is not anticipated.
Furthermore, we just released a new version (0.2.4) with several bug fixes and a few enhancements. I did not want to mess up the frameworks.yaml files so I did not touch them. As far as I can see, except for the Q2.2020 file, the version of ML-Plan always refers to the "latest" version. If this is also the version which is benchmarked everything should be fine.
> ML-Plan: Added prediction runtime for test predictions.

- amlb/benchmark.py
- amlb/job.py
- amlb/runners/aws.py
- amlb/utils/process.py
- amlb/utils/time.py
- resources/config.yaml
Ctrl-C is failing to interrupt Jobs in theur setup phase (mainly occurs in AWS mode, with instances waiting for next retry to obtain a Spot instance).
This PR replaces usage of `time.sleep` (which is difficult to interrupt) by an `threading.Event` that can be interrupted easily.
Job/Jobrunner logic has also been improved by making the state machine explicit.
> improve cancellation logic during aws job setup

- amlb/benchmarks/openml.py
- amlb/datasets/openml.py
- docs/README.md
- requirements.in
- requirements.txt
- runbenchmark.py
- tests/unit/amlb/datasets/openml/test_openml_dataloader.py
Upgrade and improvements:
- upgrades openml-python dependency to 0.12.2
- uses the `retry_policy` option introduced in `0.12.2`
- use the introduced `download_qualities` parameter of `get_task` to avoid downloading `qualities.xml` altogether.
> Upgrade openml to 0.12.2 and make use of new connectivity options

- tests/unit/amlb/utils/process/test_InterruptTimeout.py
Specifically those tests that rely on the `signal.pthread_kill` function don't work on Windows. It would be possible to make this behavior Windows compatible in some circumstances (e.g. automatically convert `sig=signal.SIGINT` to `sig=KeyboardInterrupt` on Windows). I don't know that we want to put in the effort there as the strictest escalation procedures work anyway.
> Mark tests that require unixlike signals

- frameworks/MLNet/exec.py
The latest mlnet no longer save artifacts information in `.mbconfig`. Therefore, hard-code the model path so it can be found and used in prediction.
> Update MLNet exec.py

- amlb/datasets/openml.py
Due to the conversion that openml-python does from a categorical arff column to a boolean pandas column, true/false categoricals are actually written as True/False (note capitalization) in the data but the features still describe it as true/false. This leads to a is match in the ARFF header and the actual data, which caused issues for R frameworks. 
Confirmed in #315.
> Fix mismatch between arff header and data

- frameworks/autosklearn/requirements.txt
A new scipy version is breaking the SMAC package, one of Auto-Sklearn dependencies. 
This PR aims to work-around this problem by using an older version of scipy in the install requirements of Auto-sklearn.
> [Auto-sklearn] Fixes problems with new scipy 1.7.0 version

- .github/workflows/run_all_frameworks.yml
- frameworks/autoxgboost/exec.py
- frameworks/autoxgboost/setup.sh
- frameworks/mlr3automl/exec.py
- frameworks/mlr3automl/setup.sh
Requires #324 to be resolved before R frameworks work on KC1 (part of the `validation` benchmark which is used for framework specific changes only).
Adds `mlr3automl` and `autoxgboost` to the frameworks to run CI against.
> Add R packages to 'all frameworks' CI

- amlb/runners/docker.py
- amlb/runners/singularity.py
I observed that python3 does not work in my singularity build as it is not a symlink to the system python, but something else:
```
-rwxr-xr-x 1 root root 5482296 Jul  2 07:54 python
-rwxr-xr-x 1 root root 5482296 Jul  2 07:54 python3
lrwxrwxrwx 1 root root      18 Jul  2 07:56 python3.7 -> /usr/bin/python3.7
```
I therefore propose to use the python version that's given by the `{pyv}` variable everywhere, also in the docker file.
In addition, this PR adds some brackets to the singularity file creation and removes a `RUN` which broke my build.
> Replace hardcoded python3 by python{pyv}

- frameworks/GAMA/__init__.py
- frameworks/GAMA/requirements.txt
- frameworks/shared/requirements.in
- frameworks/shared/requirements.txt
- frameworks/shared/serialization.py
As discussed in #339, the pandas version discrepancy causes issues for frameworks. Specifically there currently is a bug that prevents pickled dataframes to compatible between pandas 1.2.4 and 1.3.0. Moving forward using `parquet` as the serialized format between main and subprocesses should still offer good performance while being less likely to cause issues with mismatched versions.
Note: this is not only important for frameworks that use serialized input data, but their output (the reason AutoGluon currently fails despite already having Parquet input).
> Make Parquet the default serialization format

- .github/workflows/run_all_frameworks.yml
- amlb/datasets/openml.py
This is in particular important for the target column in classification tasks, where AutoWEKA preserves the order of those variables in the column-order for their class probabilities. And we expect those to be alphabetical. This approach seemed more sensible to me than either reading the ARFF header or the WEKA predictions file to figure out the order WEKA used.
I am not sure how to handle custom ARFF input in this scenario. Automatic splits for it aren't supported yet ([I think?](https://github.com/openml/automlbenchmark/blob/9e5b66d11a804b19595d602f3f3e7e54e544e201/amlb/datasets/file.py#L224)), but an explicit `train` and `test` file would simply have to enforce this order itself.
**Edit: Modifies the CI script to detect changed files in subdirectories too.**
> Sort categoricals in alphabetical order

- frameworks/AutoWEKA/setup.sh
Unfortunately, the previous change to `chmod` to be independent of the used SMAC version didn't work. This here works for me with singularity.
> Fix AW permissions

- amlb/benchmark.py
- frameworks/autoxgboost/setup.sh
- frameworks/mlr3automl/setup.sh
Useful to refer to a version of mlr3automl (since there are no official releases).
Will test this Monday when I have AWS access again (I can't test it on Windows - even in docker I encounter some encoding issue with installing R frameworks).
> Allow R-framework version to be specified by commit hash

- amlb/datasets/openml.py
Some datasets contain all-empty columns. Current behavior is to interpret these columns as a `STRING` ([default fallback when creating the split file](https://github.com/openml/automlbenchmark/blob/ace241b67f9e48757d3a9a199e71d3ee97715558/amlb/datasets/openml.py#L241-L249)). OpenML still has meta-data on what the (intended) type of the column is, so we can use that instead. Because OpenML does not make distinctions between `integer` and `floats` we only check the `numeric`  property last.
Addresses the first issue of #350 (the second issue is fundamentally an OpenML issue - so we hope "they" can fix it without us having to do a patch, see [EvaluationEngine#37](https://github.com/openml/EvaluationEngine/issues/37)).
Running `python runbenchmark.py autoweka openml/t/3945 test -f 0 -m docker …
> Use OML to determine data type for empty columns

- frameworks/lightautoml/setup.sh
With the current setup, an error is produced on first import. This means the final statement in the setup script exits with an error, which prevents the benchmark from running on light automl (see [lama#53](https://github.com/sberbank-ai-lab/LightAutoML/issues/53) for more information).
edit: I still noticed an error running the framework (at least on iris and APSFailure). But it's unrelated. Looks like it probably has to do with changes to the input data (encoding), I'll look into it separately.
> Install opencv-python to avoid error on import

- .github/workflows/run_all_frameworks.yml
Fixes #330:
- PRs from a fork now work the same as from a branch on the original repo (see #362 as example). The previous implementation erroneously tried to checkout the working branch instead of the merge head, which was impossible if the branch lived on a fork. We avoid it altogether by setting tracking through `git branch` instead of `git checkout`, so our `HEAD` stays on the merge commit. There's also a little optimization to only fetch the `GITHUB_BASE_REF` instead of all branches and tags.
- The difference between the merge commit and the base branch is now correctly found by comparing to the point where the branch branched off.
It does **not** add unit test on the unmerged branch, as suggested in #330.
> Fix CI to work from forks and correctly diff to master

- frameworks/mljarsupervised/exec.py
Models trained with a boolean target would output integer label predictions ([mljar#442](https://github.com/mljar/mljar-supervised/issues/442)). This patch addresses it by specifically looking at this mismatch, and if so converting the target labels back to boolean values. Additionally the probabilities_labels are now explicitly passed, to make sure there is no accidental mismatch.
This issue lead to failure in `kc1`.
> [mljar-supervised] Patch predictions for boolean target

- amlb/results.py
Sometimes labels are provided as non-str (in particular boolean for e.g. kc1), which does not work when we index on them as column names later.
FLAML was affected by this (kc1), I verified locally with a docker run that the patch solved the issue.
> Convert probabilities_labels to str

- frameworks/TPOT/__init__.py
TPOT seems to work fine without imputation: it was probably not the case in the past, but it works fine now, so as it is the only non-trivial framework for which we do imputation, let's remove this.
> Disable imputation of missing values for TPOT framework

- amlb/utils/os.py
- frameworks/H2OAutoML/exec.py
- frameworks/MLNet/exec.py
- frameworks/autosklearn/exec.py
- runbenchmark.py
Use more standard approach of adding an underscore when param conflicts with builtins, instead of removing a letter that makes it look like a typo.
> Tidy up: renamed bad filtr param

- frameworks/lightautoml/exec.py
When processing the results, if `truth` is returned it is processed based on `is_encoded` - regardless of if only the predictions are encoded or also truth ([here](https://github.com/openml/automlbenchmark/blob/c6eb3784ddde723fc4c7a3230886b1a67d142cb3/amlb/results.py#L290-L298)).
I'm not entirely sure what the original reason was, but it seems to me that there is no good reason for allowing the frameworks return `truth` (or even pass labels of the test data in the first place)? I'd be curious to know why it's a thing (and consequently see if perhaps we should rework that in the future).
> Fix LAMA - don't return `truth`

- amlb/results.py
Some frameworks like AutoGluon expose additional columns to the results file.
Those should always appear after the metrics.
> Ensure that framework's extra result columns always appear at the end.

- amlb/runners/aws.py
make blocks from instance logs and surround them with easily searchable and identifiable pattern.
This is a workaround until I find time to add support for one logger per local job.
> Improve local logs in AWS mode when many instances in parallel

- amlb/runners/aws.py
- amlb/utils/core.py
Add instance id to each line of the local console to make the logs grepable.
> Improve readablity of logs in AWS mode

- amlb/results.py
- resources/config.yaml
Avoid annoying duplicate errors when there's no result due to AWS error:
```
AWSError: InsufficientInstanceCapacity; Unsupported metric `None`
```
and retry using default job scheduler retry policy on `InsufficientInstanceCapacity` error.
> Improve error handling in AWS mode

- amlb/results.py
After remote instance was killed by `amlb` as it was hanging (no CPU activity), got the following error:
```
[ERROR] [amlb.job:06:06:28.967] Job `xxx` failed with error: 'Namespace' object has no attribute 'higher_is_better'
Traceback (most recent call last):
File "/home/automl/automlbenchmark/amlb/runners/aws.py", line 358, in _run
return self._wait_for_results(_self)
File "/home/automl/automlbenchmark/amlb/runners/aws.py", line 448, in _wait_for_results
raise AWSError("Aborting instance {} for job {}.".format(job.ext.instance_id, job.name))
amlb.runners.aws.AWSError: Aborting instance i-0400496638b60e80a for job xxx.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/automl/automlbenchmark/amlb/job.py", line 115, in start …
```
> Fix bug when handling `NoResult` if the remote instance was killed

- amlb/runners/aws.py
- amlb/utils/core.py
- resources/config.yaml
App was expectiong message `Server.SpotInstanceTermination` but was `Server.SpotInstanceTermination: Spot instance termination`
Therefore we need to revert the search string logic.
> AMLB failed retrying on Spot forced termination

- amlb/benchmark.py
- amlb/datasets/openml.py
- amlb/results.py
- amlb/runners/aws.py
- amlb/runners/container.py
- amlb/utils/time.py
- resources/config.yaml
- runbenchmark.py
By using the `--resume` option, the benchmark app will skip the duplicated jobs (ie. the jobs for which there's already an entry in `output_dir/results.csv`).
This is especially useful in AWS mode when there can be failures due to instances unavailability: in this case, an entry is created in `failures.csv` but not in `results.csv`, so re-rerunning the same benchmark later with the `--resume` option will run only the missing jobs.
> Option to resume benchmark or rerun missing results based on previous results

- .github/workflows/stable-tag.yml
Major/minor/patch versions can't use more than one digit because it relies on alphabetical order. I don't think this will be an issue, but I'm not sure how to fix this without making the script significantly more complex (by including a version parser).
> Add a workflow to tag latest `v*` release as `stable`

- resources/constraints.yaml
For ease of reproducibility, we want to include our experimental setup in the constraints file. For our experiments we increase the volume size to 100gb and require gp3 volumes (general purpose SSD).
> Add constraints for v2 benchmark

- amlb/job.py
- amlb/runners/aws.py
- tests/unit/amlb/job/dummy.py
- tests/unit/amlb/job/test_MultiThreadingJobRunner.py
- tests/unit/amlb/job/test_SimpleJobRunner.py
Letting the job runner handle the rescheduling logic to ensure that the job can't be acted upon by its current worker after being rescheduled.
> Fix AWS random cancel issue

- resources/frameworks_2021Q3.yaml
Made the previous version abstract to avoid accidentally running the
wrong version of GAMA for the benchmark.
> Add a GAMA configuration intended for benchmarking

- amlb/benchmarks/openml.py
- amlb/resources.py
- docs/README.md
- runbenchmark.py
We (me, @louquinze, @eddiebergman) are currently facing https://github.com/openml/openml-python/issues/1123 which prevents us from benchmarking string datasets with the AutoML benchmark because we cannot upload the datasets to the server. As a remedy, we uploaded them to the testserver (after removing the columns in question) and would now like to use the with the AutoML benchmark.
This PR adds support for the domain `"openmltestserver"` that basically reuses the OpenML logic.
> Add support for the OpenML test server

- frameworks/RandomForest/__init__.py
- frameworks/TunedRandomForest/__init__.py
- frameworks/shared/caller.py
Sparse targets are not supported in scikit-learn 0.24.2, and are used with tasks 360932 and 360933 (QSAR) in the benchmark.
Unfortunately I can not test the change since I am unable to generate docker images (a connection issue locally, and the `Dockerfile not found`  error on the server). @sebhrusen can you please test? :(
> Unsparsify target variables for (Tuned)RF

- amlb/benchmark.py
- runbenchmark.py
Also use `openml.cache_directory` instead of `openml.get_cache_directory()` to read the default cache folder, as the latter doesn't point to the root of the cache folder.
> Openml must be configured when loading the tasks

- .github/workflows/versioning.yml
In our current typical release scenario a moot point. But whenever a release needs to re-done this is easier (as removing the `tag` simply sets the release back to draft, which means `release:created` is never hit a second time).
> Switch from release:created to release:published

- amlb/datasets/file.py
- amlb/datasets/fileutils.py
Currently amlb benchmark yaml file doesn't accept s3 url. This is useful when users want to benchmark on AWS machines with their own private datasets.
This PR adds the ability to parse s3 url and download the file. Users will need to have AWS credentials setup on the given machine to access the resource if it's not publicly available.
> Accept datasets stored in s3

- .dockerignore
@PGijsbers I guess it was the same issue you were getting on Windows, right?
```
cannot locate specified Dockerfile: frameworks/constantpredictor/.setup/Dockerfile
```
after cleaning up the `.dockerignore` it seems to work.
> Failed to build docker images from linux

- frameworks/TunedRandomForest/custom_validate.py
- frameworks/TunedRandomForest/exec.py
- frameworks/TunedRandomForest/requirements.txt
Specifically for each value of `max_features` to try, an equal time budget is allotted, with one additional budget being reserved for the final fit. This does mean that different `max_features` can lead to different number of trees, but it keeps it simple. Tested from docker (`test test`) and aws (`openml/s/269 -t Airlines_DepDelay_10M`).
I realize it's very similar to the RandomForest at this point, the RandomForest baseline is just a special case were no values for `max_features`  are tried. If that's alright, I would like to move forward as is for now. In the future it can be refactored so that `RandomForest` and `TunedRandomForest` use the same code but with a different configuration (unless there's a good reason to keep them separate).
> Iterative fit for TunedRandomForest to meet memory and time constraints

- frameworks/TPOT/__init__.py
- frameworks/hyperoptsklearn/__init__.py
- frameworks/oboe/__init__.py
In a previous iteration it was encoded as a numpy file, but now it's
serialized to JSON which means that results.probabilities is simply a
string if imputation is required.
> Signal to encode predictions as proba now works

- amlb/datasets/openml.py
Technically monkeypatch xmltodict function used by openml when reading the features xml
See #350
> Monkeypatch openml to keep whitespace in features

- frameworks/autosklearn/setup.sh
- frameworks/shared/caller.py
Ello,
CC: @mfeurer 
This PR copies over the environment variables `TMP`, `TMPDIR` and `TEMP` into the environment in which a framework is run. This allows users to specify where automlbenchmark and any underlying framework should place there tmpfiles.
**context**
As part of our automated benchmarking with auto-sklearn, we were filling up the `/tmp` directory of some of our nodes. This would also cause larger runs to eventually crash due to memory issues, as well as causing issues for other users of our cluster.
Debugging why it was not going into the unlimited `TMPDIR=/tmp/slurm_xxxx` folder provided by our slurm cluster, we found that `automlbenchmark` would remove any env variables that were set before running a framework.
We can not pass an argument to `autosklearn` to delete the …
> Respect TMP, TMPDIR, TEMP

- amlb/utils/process.py
By default it can use cp1252 decoding which sometimes raises an error and halts the process.
> Ignore decoding errors on Windows

- amlb/runners/aws.py
- resources/config.yaml
Having properly tagged AWS objects can be a requirement in some companies to be able to launch and administrate those objects (used internally at H2O.ai), so I added a non-invasive way of specifying custom tags for all AWS created created by the `amlb` app.
> Allow custom tag for all AWS entities

- amlb/runners/docker.py
This line `**/.setup` in `.dockerignore` denies 
```bash 
python3 runbenchmark.py ... -m docker -s force
```
execution, e.g.: `automlbenchmark/frameworks/TPOT/.setup/Dockerfile`.
And to avoid docker created files to be owned by `root` on host filesystem.
> For docker to work and work better

- frameworks/AutoGluon/exec.py
- frameworks/AutoGluon/setup.sh
- resources/frameworks.yaml
- resources/frameworks_latest.yaml
- resources/frameworks_stable.yaml
PR to add support for AutoGluon v0.4
- Updates install from source logic to align with v0.4
- Added `AutoGluon_hq` and `AutoGluon_gq` presets that represent mid-way points between the quality of `AutoGluon_bestquality` and the inference speed of `AutoGluon`.
- Added loading test data prior to inference for a more genuine inference latency (previously loading data from file was included in inference time)
- Added `predictor.persist_models('best')` call to avoid loading models from disk during inference (for more genuine inference latency estimates).
> Update to support AutoGluon v0.4

- frameworks/hyperoptsklearn/setup.sh
Ello,
More fixes, this time `hyperoptsklearn` no longer exists on PyPi so I updated the setup.sh file for it to just install from github.
I've also extended the script slightly to allow for `#sha` to be allowed as the `$VERSION` argument. 
The default version for hyperoptsklearn is 'latest' as defined in `resources/frameworks.yaml` such that the `hyperoptsklearn` and `hyperoptsklearn:latest` would both work by installing from github. 
However `hyperoptsklearn:stable` would attempt to install from PyPi and hence fail.
Feel free to change the target branch once again, I'm not sure where contributions generally go for `automlbenchmark`
```bash
python runbenchmark.py -s only hyperoptsklearn # Works
python runbenchmark.py -s only hyperoptsklearn:latest # Works
python runbenchmark.py -s only …
```
> Updated setup.py for `hyperoptsklearn` as it no longer uses PyPi (also now accepts shas)

- docs/benchmark_datasets.html
Adds a redirect for a url in the 2019 paper. It redirects to the old content (but in markdown format).
> Add redirect for dataset page

- frameworks/mlr3automl/setup.sh
- resources/frameworks.yaml
- resources/frameworks_latest.yaml
- resources/frameworks_stable.yaml
Sorry, I'm doing these pull requests small and piecemeal as I diagnose some issues on our benchmarking tool.
My expectation is that any framework can be used with the tags 'stable' or 'latest' but perhaps this is incorrect.
* `frameworks_stable.yaml` didnt include 'lightautoml' but it's supported by it's `setup.sh` so I included it in.
* `frameworks_{stable,latest}.yaml` didn't include MLNet. Looking at the `setup.sh`, I included it in `frameworks_latest.yaml`. I'm unsure what you'd like to do about the 'stable' version. The simplest solution is convert both 'stable' and 'latest' to the empty string as defined in it's `setup.sh` so that it can be used with both tags.
> Included lightautoml in frameworks_stable

- resources/config.yaml
Closes #512.
Update referenced AMIs in default config to Ubuntu 22.04 LTS images from last week (2023-05-16).
> maint: upgrade AMI to Ubuntu 22.04 #512

- amlb/frameworks/definitions.py
- frameworks/flaml/setup.sh
- resources/frameworks_stable.yaml
Supersedes #414
todo: add a check that `flaml` can't be invoked if `flaml_benchmark` is already installed (it is currently not possible to switch behavior just based on hyperparameter configuration).
> Add `flaml_benchmark`

- frameworks/autosklearn/__init__.py
- frameworks/autosklearn/exec.py
Use pandas dataframes with `autosklearn>=0.15`, instead of the encoded numpy arrays.
This is preferred because it is more "auto" and because it makes inference time measurements more comparable across frameworks.
note: this is on top of the `measure_inference_time` PR #532.
@eddiebergman @mfeurer are there any other changes that should be made to account for the switch?
> Allow newer autosklearn versions to use the pandas data instead

- .github/workflows/run_all_frameworks.yml
- amlb/benchmark.py
- amlb/datasets/openml.py
- amlb/results.py
- amlb/runners/docker.py
- frameworks/AutoGluon/__init__.py
- frameworks/AutoGluon/exec.py
- frameworks/GAMA/__init__.py
- frameworks/GAMA/exec.py
- frameworks/H2OAutoML/__init__.py
- frameworks/H2OAutoML/exec.py
- frameworks/RandomForest/__init__.py
- frameworks/RandomForest/exec.py
- frameworks/TPOT/__init__.py
- frameworks/TPOT/exec.py
- frameworks/TunedRandomForest/__init__.py
- frameworks/TunedRandomForest/exec.py
- frameworks/autosklearn/__init__.py
- frameworks/autosklearn/exec.py
- frameworks/constantpredictor/exec.py
- frameworks/flaml/__init__.py
- frameworks/flaml/exec.py
- frameworks/lightautoml/__init__.py
- frameworks/lightautoml/exec.py
- frameworks/mljarsupervised/__init__.py
- frameworks/mljarsupervised/exec.py
- frameworks/shared/callee.py
- frameworks/shared/caller.py
- resources/config.yaml
**help wanted:** I am posting this now since it would be nice to have some feedback. I need merge this very soon in order to run experiments on time.
---
This PR introduces improved measurements for inference time, there are two major changes:
- inference time is now to be measured the same way across frameworks: everything from reading from disk to producing predictions
- inference time is measured for different dataset sizes, created by sampling with replacement from the test set
A few notes:
Current implementation’s result file after running `python runbenchmark.py FRAMEWORK -t iris -f 0` for `constantpredictor`, `tpot`,  and `autogluon`:
```
id,task,framework,constraint,fold,type,result,metric,mode,version,params,app_version,utc,duration,training_duration,predict_duration,models_count, …
```
> Measure inference time

- amlb/datasets/openml.py
- frameworks/AutoGluon/__init__.py
- frameworks/GAMA/__init__.py
- frameworks/H2OAutoML/__init__.py
- frameworks/RandomForest/__init__.py
- frameworks/TPOT/__init__.py
- frameworks/TunedRandomForest/__init__.py
- frameworks/autosklearn/__init__.py
- frameworks/flaml/__init__.py
- frameworks/lightautoml/__init__.py
- frameworks/mljarsupervised/__init__.py
These files have categorical values numerically encoded and missing values imputed, which makes them usable for any scikit-learn algo. This preprocessing can take considerable time and is excluded from time measurements currently, but should be included at some point in the future.
> Add scikit_safe inference time measurement files

- amlb/datasets/openml.py
- resources/config.yaml
Measuring inference time on very wide datasets is problematic if the batch size is sufficiently big. 
This stems from two issues:
- Sometimes the dataset will get to be too big to fit in memory (possibly after preprocessing), and
- the automl framework is unaware of the constraint to need to predict on batches of data greater than the training data itself. This isn't a problem in and of itself, but may lead to exceeding total allowed job time which leads no results and a waste of compute time.
This PR makes it so that it is possible to only measure inference time on batches that do not exceed the initial dataset size.
The first issue should be addressed if this option is turned on in almost all cases, as the batch size should never exceed the dataset size.
The second issue may remain, but …
> Optionally limit inference time measurements by dataset size

- frameworks/AutoGluon/exec.py
Updated max_memory to 0.4 as when tested it resulted in no crashes. The 0.1 default is overly conservative. For batch_size=1 in inference, this gives ~2x faster inference speed on average as more frequently models are able to fit into memory using this raised limit.
> Update AutoGluon `max_memory` from 0.1 to 0.4 in persist_models

- resources/frameworks_2023Q2.yaml
Add `optimize_for_deployment` for AutoGluon_hq
This disables some of the post-fit logic in favor of a more optimized fit process that reduces disk usage by >10x and reduces overall fit time without any compromise to result quality or inference speed.
Not necessarily critical for the upcoming benchmark run, but it will lead to slightly faster training times due to only the necessary models being refit, rather than all models being refit, making it less likely that AutoGluon goes significantly above the time limit.
> Add `optimize_for_deployment` for AutoGluon_hq

- frameworks/AutoGluon/exec.py
High quality presets perform a post-fit step which takes 10~15% of total time. To autogluon still only uses roughly `max_runtime` for its entire fitting procedure, we reduce the `max_runtime` communicated to autogluon by 10% which means in most cases autogluon should produce a model within the given time constraint. This is to ensure comparisons across frameworks remain fair and interpretable.
> Reduce training time by 10% if a high_quality preset is used

- frameworks/AutoGluon/exec.py
- frameworks/DecisionTree/exec.py
- frameworks/GAMA/exec.py
- frameworks/H2OAutoML/exec.py
- frameworks/MLNet/exec.py
- frameworks/MLPlan/exec.py
- frameworks/RandomForest/exec.py
- frameworks/TPOT/exec.py
- frameworks/autosklearn/exec.py
- frameworks/constantpredictor/exec.py
- frameworks/flaml/exec.py
- frameworks/hyperoptsklearn/exec.py
- frameworks/lightautoml/exec.py
- frameworks/mljarsupervised/exec.py
Standardized markers are useful for more quickly identifying in which stage of `exec.py` errors/timeouts occur.
One more thing to roll into #279 later.
> Add identical markers to identify fit/inferencetime/predict stages

- amlb/runners/aws.py
This can be useful to see how long instances were available before errors occurred (identify e.g., start up failures).
> Add start_time and stop_time to failure log

- .github/workflows/run_all_frameworks.yml
- frameworks/NaiveAutoML/__init__.py
- frameworks/NaiveAutoML/exec.py
- frameworks/NaiveAutoML/requirements.txt
- frameworks/NaiveAutoML/setup.sh
- resources/frameworks.yaml
- resources/frameworks_2023Q2.yaml
- resources/frameworks_latest.yaml
- resources/frameworks_stable.yaml
Adding NaiveAutoML 🎉
@fmohr @mwever  could you have a look at my usage of NaiveAutoML? I did the integration purely based of your docs and source code, so it is possible I misunderstood some of the usage.
Some questions:
- I noticed NAML tracks memory usage, but is there a way to provide it with a memory constraint?
- I wasn't able to get reproducible behavior for providing a target (`y`) the was a pandas series of str/categorical. One time it froze, another it would spew errors, so I couldn't open an issue. So for now within AMLB I decided to use the option for using an encoded target variable.
- Should we set `execution_time`? A fixed timeout regardless of `timeout` or `dataset` size seems prone to failure. Or does it adapt if left at default? If it's currently fixed to 10 seconds, I …
> Add Naive AutoML integration

- amlb/utils/config.py
- amlb/utils/process.py
- amlb/utils/serialization.py
- amlb/utils/time.py
- pyproject.toml
- requirements-dev.txt
As part of a larger effort to improve developer experience (#566), I started adding `mypy` to the dev tool chain.
This PR adds a minimal configuration that checks as I am following the [using mypy with an existing codebase](https://mypy.readthedocs.io/en/stable/existing_code.html) recommendations. 
This PR adds mypy only for `amlb.utils`.
The `mypy` configuration globally ignores the "attr-defined" error, because of the `amlb.utils.core.Namespace` class which uses dynamically created attributes (technically not even that, but it is mimicked with `__getattr__`). I tried to narrow down the filtering of this error by just the `Namespace` class (either through configuration, or by redefining `Namespace` as `Any` for type checking purposes), but unfortunately I could not get that to work - so …
> Start adding static type checking

- docs/readme.md
Closes #576. Adds back a readme that was removed in #565. It only puts back part of the readme, since most of the documentation is now moved to the doc pages where it is split up across multiple files instead. That said, it's probably good to re-evaluate what to put in the readme (I simply updated it quickly now to fix the issue).
> Add back a readme file

- docs/website/data.html
- docs/website/visualization.html
- docs/website/welcome.html
We want to make it easier to redirect traffic coming from our published papers in the future. For example, we might move the visualization tool, or present new results. In those cases, we want readers of the paper to still find the newest (working) data/visualization/documentation.
> Add redirect pages to easier redirect traffic after publication

- examples/custom/extensions/Stacking/exec.py
- examples/custom/extensions/Stacking/requirements.txt
- examples/custom/extensions/Stacking/setup.sh
- examples/custom/frameworks.yaml
Fixes #593.
* Update to match changes of new .setup/setup_env layout
* Update dependency to scikit-learn 1.3, which has a full stack of supported dependencies for Py 3.9
> Update Stacking example to work out of the box on Python 3.9

- amlb/datasets/file.py
- frameworks/AutoGluon/exec_ts.py
- frameworks/shared/utils.py
- requirements.in
- requirements.txt
- tests/unit/amlb/datasets/file/test_file_dataloader.py
Fix several minor bugs in the time series benchmark:
- ensure that `item_id` column is parsed as a string. If the column is parsed as an integer, it may lead to a different sorting order, which in turn introduces mistakes to seasonal error calculation.
- make sure that AutoGluon respects the random seed provided in the config
- add `s3fs` & `fsspec` dependencies that are necessary to enable pandas to load datasets from S3
> Fix minor bugs in time series forecasting

- frameworks/AutoGluon/exec.py
- frameworks/AutoGluon/setup.sh
Made a few updates to align AMLB with AutoGluon 1.0's API.
Note that all changes are backwards compatible. For AutoGluon 1.0 exclusive logic, I added if/else checks so it continues to work with older versions: Further, the mainline AMLB code works with AutoGluon 1.0 already as old methods were deprecated but not removed, it will just log deprecation warnings.
Changes related to AutoGluon 1.0:
1. `persist_models` -> `persist`
2. `persist` max_memory=0.4 -> removed as it is now the default
3. `predictor.predict_from_proba` to allow for decision threshold calibration (not enabled by default)
4. Remove `silent=True` to `leaderboard` call, as it is now silent by default.
General improvements unrelated to AutoGluon 1.0:
1. Allowed `config.max_runtime_seconds` to be None when `good_quality` or …
> Update AutoGluon to 1.0 API

- amlb/benchmark.py
- resources/config.yaml
Added overhead_time_multiplier to configuration options, previously hardcoded to 2.
This will avoid situations where it is impossible to tell AMLB to not kill a job that is running for >2x the specified `max_runtime_seconds`.
> Add overhead_time_multiplier as a configurable option

- frameworks/MLNet/exec.py
- resources/frameworks.yaml
Added the required framework parameter for MLNet Telemetry, and set the environment variable for MLNet in exec.py to then opt out by default. 
This is the [original issue.](https://github.com/openml/automlbenchmark/issues/356#issue-950480518)
Cheers,
-Noah
> Issue #356, Default Telemetry (Off)

- frameworks/GAMA/setup.sh
- resources/frameworks.yaml
The repository moved from my personal account to the [openml-labs](https://github.com/openml-labs) organisation a while ago. This PR reflects that, and allows for correct installation of `:latest` (as opposed to installing whatever fork I make).
> Update the GAMA repository location

- frameworks/AutoGluon/README.md
- frameworks/AutoGluon/exec.py
This pull request introduces enhancements to the AutoGluon framework to support the generation and saving of learning curve artifacts when running automlbenchmark. Key modifications of this PR include utilizing AutoGluon's learning curve parameter if the user specifies the appropriate config flags in their framework definitions. 
```
AutoGluon_curves_true:
extends: AutoGluon
params:
learning_curves: True
_save_artifacts: ['learning_curves']
```
```
AutoGluon_curves_test:
extends: AutoGluon
params:
learning_curves: True
_include_test_during_fit: True
_save_artifacts: ['learning_curves']
```
```
AutoGluon_curves_parameters:
extends: AutoGluon
params:
learning_curves:
use_error: True
_curve_metrics:
binary: ["log_loss", "accuracy", "precision", "recall", "f1", "roc_auc"]
regression: …
```
> [AutoGluon] Added Support for Learning Curve Artifacts

- .github/workflows/run_all_frameworks.yml
- amlb/benchmarks/openml.py
- amlb/benchmarks/parser.py
- amlb/datautils.py
- amlb/results.py
- amlb/utils/core.py
It's not perfect, but it's progress. There are a bunch of different functions with many code paths. Also a number of functions which rely on some pandas internals for typing. I would refactor this for clearer type hints, but I don't want to refactor without test coverage. So I'll merge this as is for now (it's a step in the right direction), and revisit.
> Add type annotation for benchmark parser module

- frameworks/AutoGluon/README.md
- frameworks/AutoGluon/exec.py
You can configure callbacks for AutoGluon through configuration, e.g.: 
```yaml
AutoGluonES:
extends: AutoGluon
params:
callbacks:
EarlyStoppingEnsembleCallback:
patience: 5
```
Should probably also be added to the time series script (might be worth at some point trying to see what can be stored in a shared module?)?
> Add generic callback configuration logic

- frameworks/AutoGluon/setup.sh
- Update AutoGluon to use [uv](https://github.com/astral-sh/uv) instead of pip for installation in setup.sh This aligns with mainline AutoGluon now switching to `uv` for its install instructions.
- The switch to `uv` reduces AutoGluon installation time from ~10 minutes to ~40 seconds on EC2. This also avoids [a bug in pip where it fails to install AutoGluon](https://github.com/autogluon/autogluon/issues/4515).
- Removed setuptools and wheel installs, as they aren't needed by `uv` and there is a bug in torch 1.4.x that causes an exception if setuptools is installed at the same time.
- Will now install from source in `non-editable` mode. Previously it would install in `editable` mode, which could cause bugs if running AMLB locally alongside a pre-existing local AutoGluon install. This is …
> Update AutoGluon to use uv during setup.sh

- amlb/benchmark.py
- amlb/runners/aws.py
- runbenchmark.py
Add jobhistory argument to runbenchmark.py
This allows the user to specify the specific path to the prior results file when resuming a run, rather than it being tied to the expected output file path on the local machine (which isn't the case when running via AWS mode and not continuing to use the original host instance)
For example, from s3:
```
python runbenchmark.py AutoGluon:stable test test --resume --jobhistory s3://automl-benchmark-ag/aggregated/ec2/2024_10_25/results.csv
```
If the user does not specify `jobhistory`, then the logic remains identical.
I also did some minor code cleanup in `runbenchmarks.py` to reduce code dupe.
> Add jobhistory argument to runbenchmark.py

- .github/workflows/run_all_frameworks.yml
- .github/workflows/run_pytest.yaml
Primarily to upload the CodeCov coverage to have a base reference, i.e., should close #671
> Run CI on master

- amlb/runners/docker.py
ARG is used for noninteractive because it does not need to persist into the container runtime
> Adopt modern syntax for setting env variables

- amlb/benchmarks/file.py
- amlb/benchmarks/openml.py
- amlb/datasets/openml.py
- tests/unit/amlb/benchmarks/test_openml.py
Check if oml_id is a valid integer before trying to load the task. This sometimes does not happen by default. (Only get_suite supports string ids.)
I am not sure if this behavior is different in the new OpenML API.
> Tiny bug : oml_id must be an int in load_openml_task

- frameworks/FEDOT/exec.py
- resources/config.yaml
Hi!
Fix for FEDOT prediction timer.
> Minor comment: You should time only one of these predict calls, not both, otherwise your predict time will be twice as long as it > should be.
Closes #581
> FEDOT prediction timer

- amlb/benchmark.py
- amlb/utils/process.py
- tests/conftest.py
- tests/resources/frameworks.yaml
- tests/resources/frameworks/setup_fail/__init__.py
- tests/resources/frameworks/setup_fail/setup.sh
- tests/unit/amlb/benchmarks/test_benchmark.py
If we detect an error during setup, we want to stop the benchmark process immediately, instead of continuing.
Currently, the failed process goes unnoticed and often results in unexpected errors like missing dependencies during the execution of the `exec.py` script.
> Error when frameworks installation script fails

- amlb/logger.py
- resources/config.yaml
Relates to #664 
Actually - perhaps the use of `io.StringIO` is a bit overkill here? How many print statements without newline are we expecting realistically? We could also eat the overhead and use regular string concatenation (still wouldn't solve root cause).
> Check if stream is already closed

- amlb/benchmarks/openml.py
- amlb/datasets/openml.py
This should fix the issue with arff files not being downloaded in time to generate data splits.
> Load data should download data to disk

- amlb/benchmark.py
- amlb/data.py
- amlb/datasets/file.py
- amlb/datasets/openml.py
- amlb/resources.py
- amlb/results.py
- amlb/utils/cache.py
Switch to functools for caching to reduce the number of custom solutions (I imagine part of the reason this was custom written was the lack of `cached_property` in Py3.6). 
There is one "major" distinction. The old mechanism created a per-instance cache. This is preserves for properties through `cached_property` but is _not_ reserved for methods with `cache`. As far as I can tell, this isn't really a problem: 
* Few methods use caching.
* Of those that do, most are inexpensive, so if they do now incidentally do the work one extra time, it's not a big deal.
* But most importantly, most of these are on objects, e.g. FileDataset, of which there not normally more than one instance at the same time or which are often cleared together (splits). Since the benchmark is run sequentially (in the …
> Switch to functools for caching
