runbenchmark.py

https://github.com/openml/automlbenchmark/issues/24

ISSUE-24: auto-create default logs dir under current directory

---

frameworks/AutoWEKA/exec.py

https://github.com/openml/automlbenchmark/issues/30
AutoWEKA forged command contains several path parameters: those should be quoted as they may contain spaces.

ISSUE-30: quote path params in AutoWEKA command

---

automl/docker.py

properly handle exception when running docker container, especially on keyboard interruption

Docker mode: ensure that the docker container is killed on exception

---

docs/automl_overview.md

- Add GAMA to the info page on AutoML systems.
- Sort the entries so that they are actually in alphabetical order as described in text.

Add GAMA. Fix alphabetical order.

---

amlb/benchmark.py
frameworks/AutoWEKA/__init__.py
frameworks/H2OAutoML/__init__.py
frameworks/TPOT/__init__.py
frameworks/TunedRandomForest/__init__.py
frameworks/autosklearn/__init__.py
frameworks/hyperoptsklearn/__init__.py
frameworks/oboe/__init__.py
frameworks/ranger/__init__.py

ensure that the output of setup.sh is displayed live to improve debugging

Improve debuggability for framework setup

---

amlb/results.py
frameworks/RandomForest/exec.py
frameworks/shared/caller.py

Fix for regression support on Randomforest
and in general for frameworks running in their own virtual env (RandomForest is implemented as a reference example for this).

Fixed regression support on Randomforest

---

amlb/aws.py
amlb/docker.py

https://github.com/openml/automlbenchmark/issues/75

fix SetupMode namespace

---

amlb/aws.py

Custom ec2 instance types can conveniently be passed using CLI, using the extended `t` namespace (already used to customize task params locally).
```
python runbenchmark.py tpot -m aws -Xt.ec2_instance_type=t3.medium
```
Mainly useful for testing/expermenting.

AWS support: add support for task params from CLI

---

.gitignore
amlb/__init__.py
amlb/container.py
amlb/docker.py
amlb/resources.py
amlb/singularity.py
frameworks/AutoWEKA/__init__.py
frameworks/GAMA/__init__.py
frameworks/H2OAutoML/__init__.py
frameworks/RandomForest/__init__.py
frameworks/autosklearn/__init__.py
frameworks/autoxgboost/__init__.py
frameworks/hyperoptsklearn/__init__.py
frameworks/oboe/__init__.py
frameworks/ranger/__init__.py
resources/config.yaml
resources/frameworks.yaml
runbenchmark.py

This pull request is regarding #87 
I added a container class for the common methods, and implemented the particular build/run procs of each container.
Our goal honestly is to be able to run the docker images, without sudo, on our servers that only have singularity installed and we hope that this could help others with similar troubles.

Singularity support

---

amlb/singularity.py

https://github.com/openml/automlbenchmark/issues/90

Issue 90: fix Singularity support

---

frameworks/TunedRandomForest/setup.sh

Fixed venv support for tuned random forest

---

docs/README.md

https://github.com/openml/automlbenchmark/issues/112

Issue 112: fixing broken links in README.md

---

frameworks/AutoGluon/exec.py
frameworks/autosklearn/exec.py

`info` requires model artifacts

AutoGluon: ensure that models artifacts are deleted only after reading info

---

amlb/benchmark.py
amlb/docker.py
amlb/results.py
amlb/utils/process.py
resources/config.yaml

improve handling of live_output as it can cause hanging when the subprocess writes to stderr, this happens especially if there's a minor failure during setup in docker image.

Issue: Setup hangs when creating docker image

---

reports/report/config.py
reports/report/metadata.py
reports/report/results.py
reports/report/tables.py
reports/report/visualizations/heatmap.py
reports/report/visualizations/linplot.py
reports/report/visualizations/scatterplot.py

return figures and tables to manipulate them of save them anywhere.
improved normalization: can normalize against an aggregate function (e.g. 'mean') to be able to center visualizations around a specific framework.

Improved small reporting library

---

amlb/datautils.py
amlb/results.py
requirements.txt

Realted to OpenML library upgrade #62

Moving to new openml=0.10.2 version

---

resources/frameworks.yaml

ensure that constantpredictor version doesn't depend on sklearn version

Fix constantpredictor version

---

frameworks/H2OAutoML/setup.sh

H2O was installed in the right python env

---

requirements.txt

also upgraded libraries like arff parser and pandas.

OpenML upgrade

---

amlb/results.py

https://github.com/openml/automlbenchmark/issues/205

Issue 205: Fix classification metrics computation when truth values are missing some classes

---

amlb/benchmark.py
frameworks/H2OAutoML/__init__.py
frameworks/H2OAutoML/exec.py
frameworks/H2OAutoML/requirements.txt
frameworks/H2OAutoML/setup.sh
frameworks/shared/callee.py

- upgrade h2o version
- support ARFF datasets using single quote as delimiter (otherwise fails if those values delimited with ' also contain a comma).
- ensure H2O Runs in its own venv.

Fix H2O handling of some exotic ARFF datasets

---

frameworks/autosklearn/exec.py
frameworks/autosklearn/requirements.txt
frameworks/autosklearn/setup.sh
resources/frameworks.yaml
resources/frameworks_latest.yaml
resources/frameworks_stable.yaml

Auto-sklearn 0.11.1 uses a slightly different memory management than previous versions. Also, installs packaging as this was previously installed yet.

Update Auto-sklearn code to latest version

---

frameworks/mljarsupervised/__init__.py
frameworks/mljarsupervised/exec.py
resources/frameworks.yaml

Update in the `mljarsupervised` framework (for #187):
- Fixed the problem with target type in regression tasks (related to #197) (only related to `mljarsupervised` framework)
- Updated MLJAR package version (added evaluation metric, change in parameter name `seed` -> `random_state`, change in function name `predict()` -> `predict_all()`)

Fix regression target type problem and update MLJAR version

---

amlb/benchmark.py
amlb/results.py
amlb/runners/aws.py
amlb/runners/container.py
amlb/runners/docker.py
amlb/runners/singularity.py
amlb/utils/core.py
frameworks/shared/callee.py
frameworks/shared/caller.py
frameworks/shared/setup.sh
resources/config.yaml

https://github.com/openml/automlbenchmark/issues/219
also used the failing scenarios with previous 3.6 to improve error handling robustness especially when generating results.

use python 3.7 in docker and ec2 instances

---

frameworks/H2OAutoML/exec.py

new list of possible arguments available for `_save_artifacts` with H2OAutoML framework:
```yaml
_save_artifacts: [ 'leaderboard', 'logs', 'model_predictions', 'models[binary]', 'models[mojo]', 'models[json]' ]
```
`models` is still an accepted value as an alias for `models[json]` (simplest format, much smaller than others, most likely providing all needed information about the model itself).
use only the ones you need (default behaviour is `_save_artifacts: [ 'leaderboard' ]`)

H2OAutoML: add support to download binary models as artifacts

---

amlb/datautils.py
amlb/utils/core.py
frameworks/H2OAutoML/exec.py

handle correctly classification target with negative numericals

fix H2OAutoML predictions format

---

amlb/results.py

improved robustness of results processing and identify clearly errors due to the benchmark app or the framework predictions format in the results.csv

improved robustness of results processing

---

frameworks/H2OAutoML/exec.py

dummy context manager was hidding the original error

ensure that H2O errors are reported correctly to the results.csv

---

amlb/job.py

I should have ran the benchmark locally on Windows before accepting #258, turns out it broke on Windows 😓  Signal.SIGQUIT/SIGKILL don't exist on Windows, which raises an exception otherwise. This patch avoids that.

Only add SIGQUIT/SIGKILL for non-Windows systems

---

frameworks/AutoGluon/exec.py

Followup to #237 
Based on testing I've done with the `automlbenchmark/runbenchmark.py AutoGluon_bestquality test -f 0` this should resolve any issues related to uploading large files to S3 without specifying `'models'` in the save artifacts.
One thing I've noticed (has always been there but was wondering if it could be resolved):
When training AG, I see some log output that isn't coming from autogluon that breaks up logging:
```
Fitting model: XGBoost_BAG_L1 ... Training model for up to 43.66s of the 43.66s of remaining time.
0.8115	 = Validation roc_auc score
0.61s	 = Training runtime
0.01s	 = Validation runtime
Fitting model: NeuralNetMXNet_BAG_L1 ... Training model for up to 42.98s of the 42.98s of remaining time.
{ 'columns': [ ['loc', 'float'],
0.8011	 = Validation roc_auc score …
```

Fixed AutoGluon model files saving to S3 on exception

---

amlb/benchmark.py
amlb/data.py
amlb/results.py

https://github.com/openml/automlbenchmark/issues/266

expose problem type column in results.csv

---

amlb/benchmark.py
amlb/results.py
amlb/runners/aws.py
amlb/utils/core.py

https://github.com/openml/automlbenchmark/issues/268

improved registration of metrics meta info

---

amlb/datasets/openml.py

https://github.com/openml/automlbenchmark/issues/281
This is a quick fix before handling this in a more standard way with https://github.com/openml/automlbenchmark/issues/282

Exclude potential row_id attribute for openML datasets

---

.travis.yml
amlb/benchmark.py
amlb/job.py
amlb/resources.py
amlb/results.py
amlb/runners/aws.py
amlb/runners/container.py
amlb/runners/docker.py
amlb/runners/singularity.py
amlb/utils/config.py
amlb/utils/core.py
docs/README.md
resources/config.yaml

documented and grouped config properties by semantic.
add mechanism to move/rename config entries in a backwards-compatible way.

Improve config: doc + group entries by functionality

---

amlb/benchmark.py
amlb/frameworks/definitions.py
examples/custom/extensions/GradientBoosting/__init__.py
frameworks/DecisionTree/__init__.py
frameworks/H2OAutoML/__init__.py
frameworks/H2OAutoML/setup.sh
frameworks/constantpredictor/__init__.py
frameworks/shared/caller.py

added possibility to pass custom setup environment variables

improve support for custom setup 

---

amlb/runners/docker.py
amlb/runners/singularity.py
runbenchmark.py

Also, added `--logging` parameter to let user configure the log levels.

Ensure that docker logs go to a single session output

---

amlb/benchmark.py
amlb/runners/aws.py
amlb/runners/container.py
amlb/runners/singularity.py

https://github.com/openml/automlbenchmark/issues/316

Framework assertion necessary only in local mode

---

frameworks/TunedRandomForest/exec.py

Updates the old `X_enc` references (part of #337)

Update the input to the evaluation

---

.github/workflows/run_all_frameworks.yml

To also detect files present in subdirectories.
Was added on the side in #342 but we closed the PR.

Interpret globs recursively

---

frameworks/shared/serialization.py

https://github.com/openml/automlbenchmark/issues/357

Column names of serialized pandas dataframes must be strings

---

.dockerignore
.gitignore
amlb/benchmark.py
amlb/runners/docker.py
amlb/runners/singularity.py
frameworks/AutoGluon/setup.sh
frameworks/AutoWEKA/setup.sh
frameworks/GAMA/setup.sh
frameworks/H2OAutoML/setup.sh
frameworks/MLNet/setup.sh
frameworks/MLPlan/setup.sh
frameworks/RandomForest/setup.sh
frameworks/TPOT/setup.sh
frameworks/TunedRandomForest/setup.sh
frameworks/autosklearn/setup.sh
frameworks/autoxgboost/setup.sh
frameworks/flaml/setup.sh
frameworks/lightautoml/setup.sh
frameworks/mljarsupervised/setup.sh
frameworks/mlr3automl/setup.sh
frameworks/ranger/setup.sh
frameworks/shared/setup.sh

Moved generated files during setup in local/docker/singularity modes to `.setup` subfolder.

Clean up framework folders

---

frameworks/MLNet/exec.py

#353 
This fix includes two parts, one in this repo and the other in mlnet repo. I'll update here once the fix in mlnet repo gets in

fix #353 by adding label column to predict

---

frameworks/mlr3automl/exec.py
frameworks/mlr3automl/setup.sh

Since it is the defined folder for framework dependencies, similar to #377

Rename r-packages to lib

---

.github/workflows/stable-tag.yml
resources/frameworks_2021Q3.yaml

Version bump requested by @mfeurer

Add `stable` tag workflow, bump auto-sklearn

---

.github/workflows/stable-tag.yml
amlb/__version__.py
amlb/runners/container.py
frameworks/RandomForest/setup.sh
frameworks/TunedRandomForest/setup.sh
resources/frameworks_2021Q3.yaml

I'm confused as to why some commits which were already in `stable-v2` are marked as new (e.g. `stable-tag`  workflow).

[v2.0.1] Fix docker version tags

---

amlb/results.py

Fixes: https://github.com/openml/automlbenchmark/issues/432

fixes #432 add precision to runtimes in results.csv

---

frameworks/mlr3automl/setup.sh

fix for mlr3automl

---

frameworks/flaml/exec.py

- A minor fix in the framework flaml's `exec.py` to ensure compatibility

[framework update]

---

.github/workflows/runbenchmark.yml

Allows you to run `runbenchmark.py` on any branch from a dispatch.

Add workflow to manually run `runbenchmark.py` on Github Actions

---

amlb/job.py

Specifically, adding results was queued in a job executor, while checking results was directly called by the worker threads. If the worker thread checks before the executor had added results, it is possible to get into a deadlock condition. The deadlock arises from the fact that the `stop` condition is never called and the main thread will continue to wait for its END_Q signal.

Fix a race condition of checking vs adding results

---

frameworks/GAMA/exec.py
resources/frameworks_2023Q2.yaml

`goal` hyperparameter changed to `preset, fixed indentation to report on inference measurement only if it takes place

Update GAMA for v23.0.0

---

amlb/datasets/openml.py
amlb/defaults.py

Helps with #573 
supersedes #574

Make openml 0.14.0 and up compatible

---

docs/using/reproducing.md
mkdocs.yml

At a later point:
- add concrete examples that people can follow to reproduce a specific experiment
- provide an example script that parses information from the `results.csv` file to queue benchmark jobs (or, even better, properly integrate it in `runbenchmark.py`)

Add a page with some notes on reproducibility

---

amlb/benchmarks/openml.py
tests/unit/amlb/benchmarks/test_openml.py

Add tests for OpenML benchmark definitions

---

.github/workflows/run_all_frameworks.yml
.github/workflows/run_pytest.yaml
pyproject.toml
requirements-dev.txt

Note that this only covers (some) of the unit tests ~, and none of the test matrix that runs the complete benchmark workflows~.

Add code coverage to CI

---

frameworks/FEDOT/__init__.py
frameworks/FEDOT/exec.py
frameworks/FEDOT/exec_ts.py

Got out of sync. Should set up precommit CI.

Run pre-commit
